### ISSUE TITLE
Can this plugin be used to support Moodle on Heroku?

### ISSUE THREAD

**Issue by cromwellryan** [catalyst/moodle-tool_objectfs#104]
I've installed this plugin locally with an instance of Moodle. I don't _think_ it's working, but it suggests it is configured correctly (see image of settings below).
![image](https://user-images.githubusercontent.com/129756/43104813-a5234c90-8ea0-11e8-8a40-dfc425ee1db0.png)

I think I might be understanding how this is intended to work. Will this plugin push all uploads to S3 when files are uploaded for a course or private files?

Here are the settings currently:
![image](https://user-images.githubusercontent.com/129756/43104783-8a5fa3c2-8ea0-11e8-89b6-4f465b2bd30b.png)

**Comment by mattporritt** [comment]
Hi @cromwellryan ,
The aim of this plugin is sync and then serve files from Object Storage (S3 or Azure Blob) rather than from on disk (block storage). The files that it stores and serves are basically everything in `/filedir` of your Moodle's site data directory. 

You configuration looks OK. 
As the warning suggests it's best practice to not give the S3 user that is used by this plugin delete permissions on your S3 bucket. Also once you have synced most files to S3 you will slightly better performance if you enable the "prefer external objects" setting.

You can check the progress of the syncing by looking at the report located: Site administration > Reports > Object status 
An example of this report is:
![image](https://user-images.githubusercontent.com/7369127/43110087-681673ee-8f2d-11e8-8dc7-586bc372de95.png)

You can also look at the scheduled tasks to see if the `\tool_objectfs\task\` tasks are running.

I hope this helps.
Cheers,
Matt P

**Comment by cromwellryan** [comment]
Thanks Matt!The key was we hadn't configured Cron on this playground instance 🤦‍♂️ 

I'm looking into what this might look like on Heroku with ephemeral storage and, usually, unique dyno's with unshared storage for cron tasks.

We might be building a new Filesystem plugin that combines uploads and the S3 FS repository.

Thanks for the permission heads up–just kind of tooling around as we grok this setup. 😄
