### ISSUE TITLE
get_candidate_objects uses all allocated memory 

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-tool_objectfs#137]
php admin/tool/task/cli/schedule_task.php --execute='\tool_objectfs\task\push_objects_to_storage'
Execute scheduled task: Object file system upload task (tool_objectfs\task\push_objects_to_storage)
PHP Fatal error: Allowed memory size of 4294967296 bytes exhausted (tried to allocate 20480 bytes) in /var/www/site/lib/dml/pgsql_native_moodle_database.php on line 871

**Comment by brendanheywood** [comment]
Paste from chat:

a recordset won't help that much the php api itself is wrong because all of these methods expect to return an array of things so even if you use a recordset you still have to grind through it and then make a huge object in memory. So we either change the api itself to allow of an iterator, or more simply I think we hard limit each of them to say 5000 records or something

Decision: baby step add a hard limit to each of these and leave as a get_record in the short term, I think a limit is in the 200-500 range which means the cron ticks runtime should be around a couple minutes assuming we process a couple files per second

**Comment by dmitriim** [comment]
- [ ] refactor get_candidate_objects
- [ ] use recordset
- [ ] changes the logic to get records in batches

**Comment by dmitriim** [comment]
This has been fixed as par of #143
