### ISSUE TITLE
Question about how the plugin works

### ISSUE THREAD

**Issue by devdattakulkarni** [catalyst/moodle-tool_objectfs#194]
We have a use-case similar to that outlined in 'Sharing files across moodles to save disk' section of README. The slight difference is - while we do want to share some files across Moodle instances, we also want the ability to keep certain other files separate in each Moodle instance. These are files related to plugins, which may be different in each Moodle instance. I was wondering how to achieve such a separation when using objectfs as a storage layer.

**Comment by brendanheywood** [comment]
I'd be curious the know the business reasons behind such a feature, but regardless right now this isn't possible. The easiest approach would be a new feature so that you could specify that certain files from certain plugins or fileareas's should not be pushed to remote storage, these would stay local on each moodle and only the remainder would be pushed and shared. We'd probably accept a patch for this but it's not something we'd be that interested in writing ourselves. It shouldn't be too hard, similar to the other settings for when to not push, like the other conditionals:

https://github.com/catalyst/moodle-tool_objectfs/blob/master/classes/local/form/settings_form.php#L109-L119

A more complex approach where you might have multiple object stores and logic around which store to push to, seems like a lot of complexity which I'd not really want in the plugin.

**Comment by devdattakulkarni** [comment]
Thanks for the note @brendanheywood 

The main reason as I mentioned earlier is that we want to have both sharing and separation. Sharing because different Moodle instances have lot of files in common, separation because each Moodle instance can also have different plugins installed.

**Comment by brendanheywood** [comment]
Why does the separation matter though? There is no technical reason to care. As long as files are configured to not be deleted in the object store then this should be fine, because we can't track whether it's being used in other sites. At the file storage level we only deal with raw files, that layer isn't really aware of what plugin or file area is being used. If you have the file uploaded into an assignment and also into another 3rd party plugin, the file storage layer only sees and stores one file.
