### ISSUE TITLE
Mime types report not fully working on MariaDB 10.1

### ISSUE THREAD

**Issue by danielneis** [catalyst/moodle-tool_objectfs#337]
I noticed that for MariaDB 10.1 , the SUBSTR() starts at 1 and not 0. 
With this, https://github.com/catalyst/moodle-tool_objectfs/blob/master/classes/local/report/mime_type_report_builder.php#L56 needs to be changed

**Comment by scara** [comment]
Just for the record, [MDEV-14012](https://jira.mariadb.org/browse/MDEV-14012):
> When running with sql_mode=ORACLE, MariaDB should treat the second argument (the position) to "substr" in Oracle way: If position is 0, then it is treated as 1.

[Available](https://mariadb.com/kb/en/substring/) since MariaDB v[10.3.3](https://mariadb.com/kb/en/mariadb-1033-release-notes/#general).

Same issue applies to MySQL [`SUBSTRING()`](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_substring):
> A value of `0` for **_`pos`_** returns an empty string.

I'd say that only Oracle requires `0` while the others run w/ _`1` based_ numbering.

HTH,
Matteo

**Comment by brendanheywood** [comment]
I'd assume this to break a whole ton of stuff across moodle, including in core. So I'm thinking this should be closed, but should a tracker get made so this can be a runtime or install time check in moodle itself?
