### ISSUE TITLE
Unable to access moodle data directory from Amazon s3

### ISSUE THREAD

**Issue by prabhakaran8737** [catalyst/moodle-tool_objectfs#442]
I have recently migrated my moodle data director to Amazon s3. And I am using your plugin so that all the media and course content be fetched from amazon s3 instead from local file storage. Now consider, I have deleted all the content from local file system and have it only on amazon s3. All the media file and course materials seems to be broken. I have attached my configuration screenshot as well. I see test files(Pre-Signed URL Testing) are stored and plug-in can able to access it.

I have also started raised a question in [SO](https://stackoverflow.com/questions/69821065/migrate-moodle-data-to-amazon-s3?noredirect=1#comment123427052_69821065)

I am using Moodle 3.11 version
![uAaMG](https://user-images.githubusercontent.com/5249599/140080264-99cebdaa-20a3-426a-bc13-249f7b873401.png)

**Comment by danmarsden** [comment]
I posted in SO as well, but It sounds like you have manually migrated the content to S3 rather than relying on this plugin to do the work for you. I'd guess that your manual migration has put the files into a structure/path that the plugin isn't expecting. especially if you have copied your complete moodledata folder into S3 and not just the uploaded user files. (The tool_objectfs plugin does not replace the need for a normal moodledata directory, it just allows the majority of your files to be stored in S3.)

Usually you would have a Moodle site set up with a normal moodledata directory and then you would install our tool_objectfs plugin which would migrate files from moodledata to your s3 storage, relying on the plugin to perform the migration for you.

**Comment by prabhakaran8737** [comment]
Not sure where the continue the discussion, I just posted a comment in [SO](https://stackoverflow.com/questions/69821065/migrate-moodle-data-to-amazon-s3?noredirect=1#comment123427052_69821065)

**Comment by danmarsden** [comment]
yeah - I've responded there for now but will close this as it's not really a "Bug" which is what we typically use our tracker for.

**Comment by danmarsden** [comment]
btw - in future the best place for Moodle support is usually moodle.org rather than SO :-)

**Comment by prabhakaran8737** [comment]
@danmarsden until I get this resolved, SO would be better I guess. Could you please check my comment.
