### ISSUE TITLE
Getting "core plugin/corrupted archive structure" error while installing

### ISSUE THREAD

**Issue by rajib4** [catalyst/moodle-tool_objectfs#552]
Hi there,

I am getting "core plugin/corrupted archive structure" error while installing the objectfs plugin in moodle v.4.1.x. Attached a screenshot of the error page.
Please check.
![Screenshot 03-13-2023 15 50 11](https://user-images.githubusercontent.com/13391000/224675142-e3ae0b62-3ae5-4871-9a47-7b4767336252.png)

Regards,
Rajib

**Comment by danmarsden** [comment]
I would guess you get that message when trying to use the UI to install "any" plugin - I'm guessing you are missing something like the php zip extension or you have file permissions wrong in your tempdir - best place to ask for help if you can't resolve this is on the moodle.org community forums but please update us here if you are still stuck and this only affects the tool_objectfs plugin zip.

**Comment by rajib4** [comment]
Only tool_objectfs plugin zip has this problem. All other plugin zip files go through without any issue using the UI. e.g, the local_aws plugin zip file installs just fine from the UI.

**Comment by danmarsden** [comment]
The zip file looks fine to me, what Operating system is your server running? - I wonder if there's a file it can't extract... in any case I think you'll likely need to do some more investigation because as we can't reproduce it, we can't really see what might be going on there... I'm still suspicious of this being an issue with your infrastructure rather than the zip file that github is generating.

**Comment by rajib4** [comment]
Sure will do some more investigation on my end. Will update if I find the issue. 
As for the OS, we are on Debian 11 on a AMD 64bit platform. Moodle version is 4.1.2 and PHP version is 7.4.33 with additional php extensions installed including php-zip.
