### ISSUE TITLE
Help! Files Not Migrating

### ISSUE THREAD

**Issue by edmundrotimi** [catalyst/moodle-tool_objectfs#553]
I have setup migration to Digital Ocean Spaces however, I noticed the files (courses, files etc.) are not being migrated instead I get numbered folders.
![Capture](https://user-images.githubusercontent.com/48602906/226625956-1a4cd3b6-99f6-423f-bdd3-61c4247003d1.PNG)

**My configuration**
Moodle Version: 4.1.2+
PHP Verdion: 7.4

![Web capture_21-3-2023_155213_localhost](https://user-images.githubusercontent.com/48602906/226627408-7a332adc-e0f6-4f58-9773-6935cc64a673.jpeg)

![Web capture_21-3-2023_154953_localhost](https://user-images.githubusercontent.com/48602906/226627384-779d79a0-0067-41da-8081-318e7ec87b15.jpeg)
![Web capture_21-3-2023_155249_localhost](https://user-images.githubusercontent.com/48602906/226627404-134e820a-f24a-4c8d-8bdb-39a6f8c10c11.jpeg)

**Comment by danmarsden** [comment]
those are the Moodle files - keep in mind moodle stores files using the contenthash as the file name - objectfs just allows those files to be stored in object storage rather than standard disk.

if you want to read more on how Moodle does this see: https://moodledev.io/docs/apis/subsystems/files/internals
