### ISSUE TITLE
GCP settings configuration - key & secret

### ISSUE THREAD

**Issue by victoriaSys** [catalyst/moodle-tool_objectfs#610]
Hello,
I'm configuring my Google Cloud Platform (GCP) bucket and have created a key for the service account. However, I'm unsure about the values needed for the settings. Specifically, what should I use for the 'secret' and the 'key'?

From GCP, I only receive a key, but there doesn't appear to be a 'secret'. Could you clarify what values I need to enter?
Moodle version: 3.9
tool_objectfs: MOODLE_33_STABLE
Thank you.

![image](https://github.com/catalyst/moodle-tool_objectfs/assets/122214637/6dd47aea-8c4d-4da8-9a72-2f2d9798d31b)

**Comment by phette23** [comment]
Did you create an HMAC key for your service account following [Google's instructions](https://cloud.google.com/storage/docs/authentication/managing-hmackeys)? It sounds like you may have created one of Google's own SA keys but in order to use a GSB like AWS S3 you need to use an HMAC key instead. This should provide you with both an access key and a secret. There's more information on Google's pages about their [AWS compatibility](https://cloud.google.com/storage/docs/aws-simple-migration).

**Comment by victoriaSys** [comment]
Thank you very much. I have managed to create the key.
